[package]
name = "cocoon_provision"
# New package, published 23 September 2026. Built with sui 1.79.1.
edition = "2024.beta"

[dependencies]
cocoon = { local = "../journey" }

[addresses]
cocoon_provision = "0x0"
